[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://share.fusionaivideo.io"
  to = "https://google.com"
  status = 301
  force=true
