[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://console.fusionaivideo.io/*"
  to = "https://fusionaivideo.io/console/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
